;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dired-undo
        paredit-forward-kill-word
        paredit-open-round
        ))

(setq mc/cmds-to-run-once
      '(
        dired-sort-toggle-or-edit
        find-file-in-project
        paredit-kill
        text-scale-decrease
        ))
